### ISSUE TITLE
Is there a way to default the language to english

### ISSUE THREAD

**Issue by ollyando** [raiffeisensoftware/build-your-own-radar#117]
can I change the text on the search field and back to radar field to english.
see screenshot
Any ideas
![radar](https://user-images.githubusercontent.com/3979381/90826132-2b54d200-e2f7-11ea-95e7-6836ca51c2a9.PNG)

**Comment by ChristophRSG** [comment]
Hi,

sorry for the late reply.

I just defaulted back to english with the option to override the texts in the config.json file. It's included in version 3.1.1

Kind regards.
